{% set name = "skytools" %}
{% set version = "0.0.1b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/1cosmologist/skytools/archive/v{{ version }}.tar.gz
  sha256: cf2c55ff819f1f47b9f2f5e2b73347640628d6531ef480bc7f8d03f0d763ae43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0



requirements:
  host:
    - python >=3.10
    - meson-python
    - pkg-config
    - pip
  run:
    - python >=3.10
    - astropy >=5.3
    - healpy >=1.16.0
    - numpy >=2.0.0
    - scipy >=1.10
    - joblib >=1.2.0
    

test:
  imports:
    - skytools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/1cosmologist/skytools
  summary: A library of useful tools for CMB data analysis.
  license: GPL-3.0-only
  license_file: LICENSE.txt
  doc_url: https://skytools.readthedocs.io/latest/

extra:
  recipe-maintainers:
    - 1cosmologist
