{% set name = "skytools" %}
{% set version = "0.0.1b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/1cosmologist/skytools/archive/v{{ version }}.tar.gz
  sha256: 5aa3e4d8854885723d2ae43044da1dada8023de807e0accd3dfc8e8693aefb1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1



requirements:
  host:
    - python {{ python_min }}
    - meson-python
    - pkg-config
    - pip
  run:
    - python >={{ python_min }}
    - astropy >=5.3
    - healpy >=1.16.0
    - numpy >=1.23
    - scipy >=1.10
    - joblib >=1.2.0
    

test:
  imports:
    - skytools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/1cosmologist/skytools
  summary: A library of useful tools for CMB data analysis.
  license: GPL-3.0-only
  license_file: LICENSE.txt
  doc_url: https://skytools.readthedocs.io/latest/

extra:
  recipe-maintainers:
    - 1cosmologist
