{% set name = "skytools" %}
{% set version = "0.0.1b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/1cosmologist/skytools/archive/v{{ version }}.tar.gz
  sha256: e7aed19ea4b251c43adefb55e912f61b454da57599852fddd26b0e34f05af047

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1



requirements:
  host:
    - python >=3.9
    - meson-python
    - pkg-config
    - pip
  run:
    - python >=3.9
    - astropy-base >=5.3
    - healpy >=1.16.0
    - numpy >=1.23
    - scipy >=1.10
    - joblib >=1.2.0
    

test:
  imports:
    - skytools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/1cosmologist/skytools
  summary: A library of useful tools for CMB data analysis.
  license: GPL-3.0-only
  license_file: LICENSE.txt
  doc_url: https://skytools.readthedocs.io/latest/

extra:
  recipe-maintainers:
    - 1cosmologist
