{% set name = "skytools" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/1cosmologist/skytools/archive/v{{ version }}.tar.gz
  sha256: 07b2fbe5d76f1bbd7a5faf7b4780337bf85cba1c46cd0895879f8d9dd9f1e7a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0



requirements:
  host:
    - python >=3.10
    - meson-python
    - pkg-config
    - pip
  run:
    - python >=3.10
    - astropy >=5.3
    - healpy >=1.16.0
    - numpy >=2.0.0
    - scipy >=1.10
    - joblib >=1.2.0


test:
  imports:
    - skytools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/1cosmologist/skytools
  summary: A library of useful tools for CMB data analysis.
  license: GPL-3.0-only
  license_file: LICENSE.txt
  doc_url: https://skytools.readthedocs.io/latest/

extra:
  recipe-maintainers:
    - 1cosmologist
